ControlFocus("File Upload", "", "Edit1")
Sleep(500)
ControlSetText("File Upload", "", "Edit1", "F:\General\Sumanta Resume\2013-2015 Automation Selenium\6.4 Yrs_Manual & Automation_Selenium")
Sleep(200)
ControlClick("File Upload", "", "Button1")
Sleep(200)
